# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "00 23 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10.1
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Update pip
      run:  python -m pip install --upgrade pip
      
    - name: Delete old repo
      run:  rm -f working-calendar
      
    - name: Git clone repo
      run:  git clone https://github.com/evdeev/working-calendar.git && cd working-calendar
      
    - name: Install requirements
      run:  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
    - name: Parsing calendar
      run:  python main.py
      
    - name: Commit and puth
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --rfc-3339=seconds --utc)
        git commit -m "Latest data: $(timestamp)" || exit 0
        git push
      

